### PR TITLE
Update generator version to 1.16.1

### PR DESCRIPTION
**Pull request by ghost**
There were new releases, bumping this to trigger new docker image release

### CODE REVIEW

**Comment by ghost** [comment]
@ferrarimarco 🙏

**Comment by ferrarimarco** [comment]
Thanks for the PR. I've to check what's happening with dependabot, because it should have taken care of this.

**Comment by ghost** [comment]
I think it may have an issue because of the missing dependency in base image

**Comment by TomasLudvik** [comment]
It would be nice to have merged ASAP @ferrarimarco. Just spent few hours looking why something is not working, found it has been fixed in one of last releases and wondered why it is not working on my local. I have found out that I am using 9 months old Docker image. Please merge it.

**Comment by ferrarimarco** [comment]
Closing this for #38 

I've fixed Dependabot + added some linting.

**Pull request closed without merging**
