### PR TITLE
Adding in git, fixes #1

### LINKED ISSUE #1: Iooks like git needs to be added to the docker image.
`docker run -it --rm -v "$(pwd)":/usr/local/src/your-app ferrarimarco/github-changelog-generator --token $GITHUB_TOKEN --exclude-labels changelog,repo_maintenance,duplicate`

Output:
`/usr/local/bundle/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/parser.rb:250:in ``': No such file or directory - git (Errno::ENOENT)`

### PR DESCRIPTION
**Pull request by rshade**
This PR fixes the missing git package issue.

### CODE REVIEW

**Review by ferrarimarco — CHANGES_REQUESTED** [review]
Hi @rshade, thanks for your PR.

Can you please add some details (full log, what this PR does...)?

I think we need some changes:

1. Why are you upgrading every package? This leads to unreproducible builds
1. Why `bash` is needed?
1. I would rather not to include OpenSSH at this time. This is used to generate logs for GitHub, so a user may just stick with the HTTPS repo URL

Thanks!

**Comment by rshade** [comment]
@ferrarimarco thanks for the quick feedback. The real answer is to most of your questions is I stole that line from here: https://github.com/bravissimolabs/docker-alpine-git/blob/master/Dockerfile. Let me trim it down. That leads me to a question I was going to open an issue, but how do you add options like: --token $TOKEN --exclude-labels foo,bar

**Comment by ferrarimarco** [comment]
You just add the options that you like :)

The default one is `--help`, anything you specify overrides it.

**Comment by rshade** [comment]
cool I run a docker build, and it seems to build fine: 
```Sending build context to Docker daemon 66.05 kB
Step 1/12 : FROM ruby:2.4-alpine3.7
 ---> 88a05c41c573
Step 2/12 : LABEL maintainer "ferrari.marco@gmail.com"
 ---> Using cache
 ---> f569fe9e5643
Step 3/12 : RUN apk add --no-cache git
 ---> Running in 0c60b0e3ea0f

fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/5) Installing libssh2 (1.8.0-r2)
(2/5) Installing libcurl (7.60.0-r1)
(3/5) Installing expat (2.2.5-r0)
(4/5) Installing pcre2 (10.30-r0)
(5/5) Installing git (2.15.2-r0)
Executing busybox-1.27.2-r7.trigger
OK: 44 MiB in 35 packages
 ---> cd4a70e398f0
Removing intermediate container 0c60b0e3ea0f
Step 4/12 : ENV BUNDLER_VERSION 1.16.1
 ---> Running in cf5b0b4c4b47
 ---> c9fe6251e594
Removing intermediate container cf5b0b4c4b47
Step 5/12 : COPY Gemfile Gemfile
 ---> 82ce1b17db0e
Removing intermediate container 9e03ab8cff38
Step 6/12 : RUN gem install bundler --version $BUNDLER_VERSION   && bundle install --system   && gem uninstall bundler
 ---> Running in 65b2c34fd3a9

Successfully installed bundler-1.16.1
1 gem installed
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies........
Fetching rake 12.3.1
Installing rake 12.3.1
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 1.0.1
Installing i18n 1.0.1
Fetching minitest 5.11.3
Installing minitest 5.11.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
Fetching activesupport 5.2.0
Installing activesupport 5.2.0
Fetching public_suffix 3.0.2
Installing public_suffix 3.0.2
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 1.16.2
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching faraday 0.15.2
Installing faraday 0.15.2
Fetching faraday-http-cache 2.0.0
Installing faraday-http-cache 2.0.0
Fetching multi_json 1.13.1
Installing multi_json 1.13.1
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Fetching octokit 4.9.0
Installing octokit 4.9.0
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching retriable 2.1.0
Installing retriable 2.1.0
Fetching github_changelog_generator 1.14.3
Installing github_changelog_generator 1.14.3
Bundle complete! 1 Gemfile dependency, 19 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
Removing bundler
Successfully uninstalled bundler-1.16.1
 ---> 38f49755e308
Removing intermediate container 65b2c34fd3a9
Step 7/12 : ENV SRC_PATH /usr/local/src/your-app
 ---> Running in a7e32fc43bdc
 ---> fa371b349ee8
Removing intermediate container a7e32fc43bdc
Step 8/12 : RUN mkdir -p $SRC_PATH
 ---> Running in b401b255c89b

 ---> ffd0435a65a7
Removing intermediate container b401b255c89b
Step 9/12 : VOLUME $SRC_PATH
 ---> Running in 7bd738c6538c
 ---> ef15d337fe7d
Removing intermediate container 7bd738c6538c
Step 10/12 : WORKDIR $SRC_PATH
 ---> 823c45a0a02e
Removing intermediate container 6ba13a4e8c35
Step 11/12 : CMD --help
 ---> Running in 9181ef4fd869
 ---> d3a493db34a0
Removing intermediate container 9181ef4fd869
Step 12/12 : ENTRYPOINT github_changelog_generator
 ---> Running in 22638053da3d
 ---> 7b749682affa
Removing intermediate container 22638053da3d
Successfully built 7b749682affa
```

`docker run -it --rm -v "$(pwd)":/usr/local/src/your-app 7b749682affa --token $GITHUB_TOKEN --exclude-labels changelog,repo_maintenance,duplicate`

**Comment by rshade** [comment]
This only produces a usage though: `Usage: github_changelog_generator [options]`

**Comment by ferrarimarco** [comment]
Hi @rshade let me check...

**Review by ferrarimarco — APPROVED** [review]

**Comment by ferrarimarco** [comment]
Thanks @rshade, your PR has been merged :)

**Pull request merged**
